apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-nginx
  name: my-nginx
spec:
  containers:
  - image: nginx
    name: my-nginx
    envFrom:
      - configMapRef:
           name: app-config
      - secretRef:
           name: app-secret
