# Default values for voting-app-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

votingApp:
  image:
    repository: dockersamples/examplevotingapp_vote
  nodePort: 31781
  replicaCount: 1

resultApp:
  image:
    repository: dockersamples/examplevotingapp_result
  nodePort: 31364
  replicaCount: 1

postgres:
  image:
    repository: postgres
    tag: 9.6.5
  port: 5432
  replicaCount: 1

redis:
  image:
    repository: redis
  port: 6379
  replicaCount: 1

workerApp:
  image:
    repository: dockersamples/examplevotingapp_worker
  replicaCount: 1


imagePullSecrets: []
nameOverride: ""
fullnameOverride: "vapp"


podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
