apiVersion: v1
kind: Service
metadata:
  name: {{.Values.apiApp.name}}
  labels:
    name: {{.Values.apiApp.name}}
    app: {{.Values.apiApp.name}}
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: {{ .Values.apiApp.nodePort }}
  selector:
    name: {{.Values.apiApp.name}}-pod
    app: {{.Values.apiApp.name}}
