apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    name: api-service
    app: api-demo
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: {{ .Values.votingApp.nodePort }}
  selector:
    name: api-demo-pod
    app: api-demo
